### ISSUE TITLE
Where to configure the allowed/blocked groups?

### ISSUE THREAD

**Issue by szaimen** [rullzer/sharepermissions#2]
Hello,

I've just found the app and installed it. But I cannot figure out where I can allow/block sharing (inside the admin settings).

Please add those instructions to the readme, thanks!

Greetings, szaimen

**Comment by szaimen** [comment]
I also have now a lot of Warning issues in my log file. Maybe it is related?
```
[filesystem] Warning: Storage wrapper 'sharepermissions' was not registered via the 'OC_Filesystem - preSetup' hook which could cause potential problems.

GET /ocs/v2.php/search/providers/talk-conversations/search?term=share&from=%2Fsettings%2Fapps
from ipadress and user at 2021-02-06T17:51:47+01:00
```

**Comment by dahumph** [comment]
Exactly the same problem as described by szaimen. Any news on that?

**Comment by szaimen** [comment]
cc @rullzer

**Comment by rullzer** [comment]
You can't from the admin settings.
You have to the the occ command from the terminal
